on:
  push:
    paths:
      - joss/**

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: joss/paper.md

      - name: Check if PDF was generated
        run: |
          if [ -f joss/paper.pdf ]; then
            echo "PDF generated successfully!";
          else
            echo "PDF generation failed!";
            exit 1;
          fi

      - name: Create GitHub Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: joss/paper.pdf  # 将 PDF 文件附加到 GitHub 发布中

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: joss/paper.pdf
